# fly.toml app configuration file generated for fresk-cassettes on 2023-10-24T12:46:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fresk-cassettes"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
